### ISSUE TITLE
Linux v2.0.0;  index 0 has type 'float' but 'int' is expected

### ISSUE THREAD

**Issue by Alchemist650** [Aeolitus/Sephrasto#63]
Hallo, tolles neues Theme :)

Beim Start von v2.0.0, (ja gerade eben ein git pull von v1.6 auf v2 gemacht)

`Unerwarteter Fehler: TypeError: index 0 has type 'float' but 'int' is expected. Bei Fragen zum diesem Fehler bitte sephrasto.log mitsenden.`

sephrasto.log:
```
2022-02-21 21:30:42,453 | CRITICAL | Sephrasto.py::sephrasto_excepthook(46) |  TypeError: index 0 has type 'float' but 'int' is expected Traceback (most recent call last):
   File "/home/christoph/Documents/Rollenspiel/DSA/.Sephrasto/src/Sephrasto/Sephrasto.py", line 218, in editExisting
   File "/home/christoph/Documents/Rollenspiel/DSA/.Sephrasto/src/Sephrasto/CharakterEditor.py", line 120, in setupMainForm
   File "/home/christoph/Documents/Rollenspiel/DSA/.Sephrasto/src/Sephrasto/CharakterVorteileWrapper.py", line 33, in __init__
```

**Comment by brzGatsu** [comment]
Hiho, dank dir! Der fehler tritt bei mir nicht auf. Wenn du ncohmal latest ziehst, loggt sephrasto die qt version mit. Kannst du bitte verifizieren, dass du diese Versionen hast? Qt Version 5.15.2 PyQt 5.15.6. Wenn das nicht hilft werde ich an den betroffenen Stellen casts einbauen.

PS schau gerne auch auf inserem Discord vorbei: https://dsaforum.de/viewtopic.php?f=180&t=57760&p=2038641#p2038641

**Comment by Alchemist650** [comment]
2022-02-21 21:50:02,661 | CRITICAL | Sephrasto.py::__init__(76) | Starte Sephrasto v2.0.0
2022-02-21 21:50:02,661 | CRITICAL | Sephrasto.py::__init__(77) | Qt 5.15.2 PyQt 5.15.6
2022-02-21 21:50:03,271 | CRITICAL | Sephrasto.py::__init__(132) | Plugin: loaded CharakterAssistent
2022-02-21 21:50:03,275 | CRITICAL | Sephrasto.py::__init__(132) | Plugin: loaded LangerBogenBeschreibung
2022-02-21 21:50:09,175 | CRITICAL | Sephrasto.py::sephrasto_excepthook(46) | TypeError: index 0 has type 'float' but 'int' is expected Traceback (most recent call last):
File "/home/christoph/Documents/Rollenspiel/DSA/.Sephrasto/./src/Sephrasto/Sephrasto.py", line 172, in createNew
File "/home/christoph/Documents/Rollenspiel/DSA/.Sephrasto/src/Sephrasto/CharakterEditor.py", line 120, in setupMainForm
File "/home/christoph/Documents/Rollenspiel/DSA/.Sephrasto/src/Sephrasto/CharakterVorteileWrapper.py", line 33, in __init__

**Comment by brzGatsu** [comment]
Fixed in bcf03ec
