### ISSUE TITLE
Neuer Character - „Elfische Kämpferin - Kildare“ - Absturz

### ISSUE THREAD

**Issue by kgitthoene** [Aeolitus/Sephrasto#84]
N'Abend,

Ich versuchte einen neuen Character zu erstellen mit folgenden Werten:

1. Hausregeln: Keine
2. Geschlecht: Überspringen
3. Spezies: Mensch | 0 EP
4. Kultur: Tulamidenlande | 0 EP
5. Professionskategorie: 3 - Kämpfer
6. Profession: Elfische Kämpferin - Kildare | 2920 EP

Ergebnis: Absturz.

LOG:
```
2024-03-30 20:48:22,215 | CRITICAL | Sephrasto.py::__init__(144) | Starte Sephrasto v4.4.0
2024-03-30 20:48:22,215 | CRITICAL | Sephrasto.py::__init__(145) | Qt 6.6.1 PySide 6.6.1 (compiled with Qt 6.6.1)
2024-03-30 20:48:44,207 | CRITICAL | Sephrasto.py::sephrasto_excepthook(57) | TypeError: 'str' object does not support item assignment Traceback (most recent call last):
   File "/home/kthoene/.localpython/bin/venv-sephrasto-3.9.7/Sephrasto/src/Sephrasto/Sephrasto.py", line 354, in createNew
   File "/home/kthoene/.localpython/bin/venv-sephrasto-3.9.7/Sephrasto/src/Sephrasto/CharakterEditor.py", line 166, in newCharacterFromWizard
   File "/home/kthoene/.localpython/bin/venv-sephrasto-3.9.7/Sephrasto/src/Sephrasto/CharakterAssistent/WizardWrapper.py", line 39, in apply
   File "/home/kthoene/.localpython/bin/venv-sephrasto-3.9.7/Sephrasto/src/Sephrasto/CharakterAssistent/CharakterMerger.py", line 418, in xmlLesen
   File "/home/kthoene/.localpython/bin/venv-sephrasto-3.9.7/Sephrasto/src/Sephrasto/Core/Fertigkeit.py", line 115, in __deepcopy__

```

**Comment by brzGatsu** [comment]
Dank für den Report! Ist auf main schon gefixt.
