### ISSUE TITLE
Release 5.0.1 / Linux not working

### ISSUE THREAD

**Issue by kgitthoene** [Aeolitus/Sephrasto#86]
Ich habe das Release 5.0.1 herunter geladen und versucht zu installieren:
```
$ unzip Sephrasto-5.0.1.zip
$ mv Sephrasto-5.0.1 Sephrasto
$ pip install -r Sephrasto/requirements.txt    # No problems here.
$ python Sephrasto/src/Sephrasto/Sephrasto.py
```

Ausgabe:
```
Traceback (most recent call last):
  File "signature_bootstrap.py", line 77, in bootstrap
  File "signature_bootstrap.py", line 93, in find_incarnated_files
  File "/home/kthoene/.localpython/python-3.9.7/lib/python3.9/pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "/home/kthoene/.localpython/python-3.9.7/lib/python3.9/pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/kthoene/.localpython/python-3.9.7/lib/python3.9/pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Fatal Python error: could not initialize part 2
Python runtime state: initialized

Current thread 0x00007f4c47b70740 (most recent call first):
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1173 in create_module
  File "<frozen importlib._bootstrap>", line 565 in module_from_spec
  File "<frozen importlib._bootstrap>", line 666 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1058 in _handle_fromlist
  File "/home/kthoene/.localpython/bin/venv-sephrasto-3.9.7/lib/python3.9/site-packages/PySide6/__init__.py", line 64 in _setupQtDirectories
  File "/home/kthoene/.localpython/bin/venv-sephrasto-3.9.7/lib/python3.9/site-packages/PySide6/__init__.py", line 124 in <module>
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 850 in exec_module
  File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "/home/kthoene/.localpython/bin/venv-sephrasto-3.9.7-A/Sephrasto/src/Sephrasto/Sephrasto.py", line 8 in <module>
Abgebrochen (Speicherabzug geschrieben)
```

Voraussetzungen:
Python 3.9.7 Umgebung (virtual environment)
Ubuntu 22.04.4 LTS

**Comment by brzGatsu** [comment]
Hmm, der Output sagt mir leider nicht viel. Geht es, wenn du Sephrasto direkt aus dem Ordner startest, in dem die Sephrasto.py liegt? Also ion den Ordner navigieren und dann ```python Sephrasto.py```

**Comment by kgitthoene** [comment]
Ok, dann mal aus dem Verzeichnis von Sephrasto.py.
Da klappt es. Menno, ey!
Danke.

```
$ cd Sephrasto/src/Sephrasto
$ python Sephrasto.py
Path override failed for key base::DIR_APP_DICTIONARIES and path '/home/kthoene/.localpython/bin/venv-sephrasto-3.9.7/lib/python3.9/site-packages/PySide6/Qt/libexec/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/home/kthoene/.localpython/bin/venv-sephrasto-3.9.7/lib/python3.9/site-packages/PySide6/Qt/libexec/qtwebengine_dictionaries'
[7227:7249:0502/170532.281070:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
(venv-sephrasto-3.9.7)
```
Den Output nach dem Befehl bekomme ich in der Konsole.

sephrasto.log:
```
2024-05-02 17:06:31,347 | CRITICAL | Sephrasto.py::__init__(148) | Starte Sephrasto v5.0.1
2024-05-02 17:06:31,347 | CRITICAL | Sephrasto.py::__init__(149) | Qt 6.7.0 PySide 6.7.0 (compiled with Qt 6.7.0)
2024-05-02 17:06:31,801 | WARNING | Sephrasto.py::qt_message_handler(94) | Path override failed for key base::DIR_APP_DICTIONARIES and path '/home/kthoene/.localpython/python-3.9.7/bin/qtwebengine_dictionaries' (None:0, None)
```

**Comment by brzGatsu** [comment]
Das Warning kann ignoriert werden. Das Starten aus einem anderen Ordner sollte aber funktionieren, definitiv ein bug.

**Comment by brzGatsu** [comment]
Zwei unserer Entwickler mit Linux haben das Problem nicht. Ohne repro kann ich leider nichts tun, daher schließe ich den issue. Eventuell liegt es an deiner Ubuntu oder Pythonversion. Falls du den Fehler selbst debuggen kannst gerne bescheid geben. In jedem Fall werde ich schauen, dass das Logfile immer im Sephrastoordern landet, egal von welchem Ordner man startet. Vielleicht hilft das schon (vermutlich aber eher nicht).

**Comment by kgitthoene** [comment]
Die Reinstallation von PySide6 hat das ursprüngliche Problem behoben.
```
$ pip3 install PySide6 --force-reinstall --no-cache-dir
```
Nach meinen Recherchen ist dies ein Problem, das nach einem Upgrade von PySide auftreten **_kann_**!
In meiner alten Version von Sephrasto, 4.4.0, wurde PySide6~=6.6.0 verwendet, mit Version 5.0.1, PySide6~=6.7.0.

Also kein Bug in Sephrasto. Tricky.
